---
- hosts: all
  gather_facts: no
  vars:
    win_update_categories:
      - CriticalUpdates
      - DefinitionUpdates
      - SecurityUpdates
      - Updates
      - UpdateRollups

  tasks:
    # Check if there are missing Critical and Security Updates
    - block:
        - name: Checking for Available Windows Updates
          win_updates:
            category_names: "{{ win_update_categories }}"
            state: searched
          register: available_updates

        - name: Extract KB names
          set_fact:
            #kb_names: "{{ available_updates.updates | dict2items | selectattr('value.installed', 'equalto', false) | map(attribute='value.kb') | flatten }}"
            Pending_Updates: "{{ available_updates.updates | dict2items | selectattr('value.installed', 'equalto', false) | map(attribute='value.title') | list }}"
        - name: Pending Windows Updates
          debug:
            var: Pending_Updates
